= Release notes - Payara Platform Enterprise 6.31.0

== Supported APIs and Applications

* Jakarta EE 10
* Jakarta EE 10 Applications
* MicroProfile 6.1

== Improvements

* [FISH-12205] [Community Contribution - https://github.com/lprimak[LPrimaK]] Add Cache Time To Live to Application Deployment Properties

== Bug Fixes

* [FISH-9654] Fixed saving batch settings for Payara Server instances creating duplicate domain.xml lines that prevented startup

* [FISH-11174] Fixed Admin interface slow response when managing degraded server instances

* [FISH-11289] Fixed deserialization breaking with `FAIL_ON_TRAILING_TOKENS` in Payara 5.69+

* [FISH-11590] Fixed JNDI lookups failing for local JavaMail sessions

* [FISH-11967] Fixed Phone Home generating duplicate IDs

== Component Upgrades

* [FISH-11827] Upgrade `jersey.version` from `3.1.10.payara-p1` to 3.1.11

* [FISH-11947] Upgrade `EclipseLink` to 4.0.7

* [FISH-11959] Upgrade `jakarta.mail:jakarta.mail-api` from 2.1.3 to 2.1.5

* [FISH-11969] Upgrade `org.apache.felix:org.apache.felix.webconsole` from 5.0.12 to 5.0.14

* [FISH-12038] Upgrade `com.fasterxml.jackson:jackson-bom` from 2.19.2 to 2.20.0

* [FISH-12047] Upgrade `org.yaml:snakeyaml` from 2.4 to 2.5

* [FISH-12060] Upgrade `org.apache.felix:org.apache.felix.scr` from 2.2.12 to 2.2.14

* [FISH-12062] Upgrade `com.nimbusds:nimbus-jose-jwt` from 10.4.2 to 10.5

* [FISH-12086] Upgrade `io.projectreactor:reactor-core` from 3.7.9 to 3.7.11

* [FISH-12097] Upgrade `jline.version` from 3.30.5 to 3.30.6

* [FISH-12098] Upgrade `org.jetbrains.kotlin:kotlin-stdlib` from 2.2.10 to 2.2.20

* [FISH-12101] Upgrade `jakarta.activation:jakarta.activation-api` from 2.1.3 to 2.1.4

* [FISH-12103] Upgrade `jakarta.xml.bind:jakarta.xml.bind-api from` 4.0.2 to 4.0.4

* [FISH-12144] Upgrade `net.java.dev.jna:jna` from 5.17.0 to 5.18.0

* [FISH-12146] Upgrade `org.apache.felix:org.apache.felix.webconsole` from 5.0.14 to 5.0.18

* [FISH-12147] Upgrade `jaxb-impl.version` from 4.0.5 to 4.0.6

* [FISH-12172] Upgrade `org.eclipse.angus:angus-mail` from 2.0.4 to 2.0.5

* [FISH-12173] Upgrade `com.fasterxml:classmate` from 1.7.0 to 1.7.1

* [FISH-12196] Upgrade `net.java.dev.jna:jna` from 5.18.0 to 5.18.1